### ISSUE TITLE
Parallel `run_docker_container.sh` script

### ISSUE THREAD

**Issue by andre15silva** [coinse/GHRB#3]
It would be nice to be able to execute `run_docker_container.sh` in parallel.

Right now this is not possible because the script uses and removes one single named container.

**Comment by smkang96** [comment]
Hi, sorry for the late response; I was a bit occupied, due to preparation for the thing in the next paragraph. I _think_ the fix itself is simple, you can check my pull request if it would help your situation. Thanks for the suggestion though, this was an important use case to know of.

Just since we've been communicating through the platform... I also wanted to let you know I'm going to be away for about a month due to a mandatory military training thing in South Korea. I'm sure @jaeyonglee0205 will be able to capably communicate with you.

Once again, thanks for the suggestion!

**Comment by smkang96** [comment]
Since there have been no additional suggestions, I'll close the issue.

**Comment by andre15silva** [comment]
The fix seems right to me, I did something similar on my side as a hot-fix :) thanks!
